# The Docker image that will be used to build your app
image: node:20.12.0
# Functions that should be executed before the build script is run
stages:
  - build
  - test
  - deploy


before_script:
  - npm install

build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - dist/
  only:
    - main

deploy:
  stage: deploy
  script:
    - scp -r dist/ user@server:/var/www/html
  only:
    - main