# The Docker image that will be used to build your app
image: node:20.12.0
# Functions that should be executed before the build script is run
stages:
  - build
  - test
  - deploy


before_script:
  - echo "Before script section"
  - echo "For example you might run an update here or install a build dependency"
  - echo "Or perhaps you might print out some debugging details"

after_script:
  - echo "After script section"
  - echo "For example you might do some cleanup here"

build1:
  tags:
    - maven
  stage: build
  script:
    - echo "Do your build here"

test:
  tags:
    - maven
  stage: test
  script:
    - echo "Do a test here"
    - echo "For example run a test suite"

deploy:
  tags:
    - maven
  stage: deploy
  script:
    - echo "Do your deploy here"